/*
 * Arkansas state NIBRS "INCIDENT REPORT" parser — unit + contract tests.
 *
 * Run: set ELECTRON_RUN_AS_NODE=1 && node_modules\.bin\electron.cmd modules\rms\__tests__\ar-incident-parser.test.js
 * (plain `node` also works — the parser has no native deps.)
 *
 * The fixture is the REAL Tesseract OCR of a real 5-page Arkansas return with
 * every identifying value swapped for a same-shaped synthetic one. All OCR
 * damage is preserved verbatim: shredded vertical band labels, checkbox glyphs
 * (Il / IE / Bl / [J / LJ / O), the lost opening paren on the victim phone, the
 * digit/letter drift in the officer code on page 4 and the NAME values the
 * layout pass drops on the continuation page.
 */
const fs = require('fs');
const path = require('path');
const AR = require(path.join(__dirname, '..', 'ar-incident-parser.js'));

let pass = 0, fail = 0;
const ok = (n, c, x) => { if (c) { pass++; console.log('  PASS  ' + n); } else { fail++; console.log('  FAIL  ' + n + (x !== undefined ? ' -> ' + JSON.stringify(x) : '')); } };
const eq = (n, a, b) => ok(n, JSON.stringify(a) === JSON.stringify(b), { got: a, want: b });

const FIX = path.join(__dirname, 'fixtures');
function loadFixture(name) {
    // The '#' banner explains the redaction; it is not part of the OCR output.
    return fs.readFileSync(path.join(FIX, name), 'utf8')
        .split('\n').filter(l => !/^#/.test(l)).join('\n');
}
const TEXT = loadFixture('ar-incident-report.ocr.txt');
const SPARSE5 = loadFixture('ar-incident-report.page5-sparse.txt');

/* ────────────────────────────────────────────────────────────────
 * 1. detect() — must fire on this form and must NOT steal any format
 *    already handled by the inline parseRmsReport dispatcher.
 * ──────────────────────────────────────────────────────────────── */
console.log('\n[detect]');
ok('detects the Arkansas incident report', AR.detect(TEXT) === true);
ok('rejects empty text', AR.detect('') === false);
ok('rejects null', AR.detect(null) === false);
ok('rejects undefined', AR.detect(undefined) === false);
ok('rejects text with no INCIDENT REPORT title',
    AR.detect('ARKANSAS ARRESTEE # EXACT AGE Others Involved SUBJECT DESCRIPTORS') === false);

// The four formats that are detected BEFORE this one, plus legacy INFORM.
ok('does not claim the Prosecution Report format',
    AR.detect('Defendant Information\nCase Filing Information\nINCIDENT REPORT\n') === false);
ok('does not claim the Incident Summary format',
    AR.detect('Summary of\nOfficer Report Contents\nSuspect(s) - 2 Involved\nINCIDENT REPORT') === false);
ok('does not claim the Virginia field incident format',
    AR.detect('INCIDENT PAGE 1\nIncident No.\n2026-1234\nINCIDENT REPORT') === false);
ok('does not claim the Crime Report format',
    AR.detect('CRIME REPORT\nCONTROLLED DOCUMENT\nCase\nSNB2502566') === false);
ok('does not claim a bare INFORM report',
    AR.detect('Generated By: jdoe\nINCIDENT REPORT\nSupplement No: 1\nOffense(s)\nPC - 459 BURGLARY') === false);
// A mangled scan that loses BOTH "ARKANSAS" and the ORI still resolves on structure.
ok('still detects when OCR loses ARKANSAS and the ORI',
    AR.detect('INCIDENT REPORT\nEXCEPTIONAL\nCLEARANCE STATUS:\nARRESTEE #\nEXACT AGE\n' +
              'Others Involved\nDAY(S) OF INCIDENT\nMULT. ARREST INDIC.:') === true);
ok('two structural signals alone are not enough without a strong marker',
    AR.detect('INCIDENT REPORT\nARRESTEE #\nEXACT AGE') === false);

/* ────────────────────────────────────────────────────────────────
 * 2. Page splitting
 * ──────────────────────────────────────────────────────────────── */
console.log('\n[pages]');
const pageSplit = AR._internal.splitPages(TEXT.replace(/\r\n?/g, '\n').split('\n'));
const pages = pageSplit.pages;
ok('banner inference is not flagged authoritative', !pageSplit.authoritative);
eq('splits into 5 pages', pages.length, 5);
eq('page ordinals are 1..5', pages.map(p => p.index), [1, 2, 3, 4, 5]);
ok('page 1 starts at line 0 (its title never survives standalone)', pages[0].from === 0);
eq('only page 5 is a continuation page', pages.map(p => p.isContinuation), [false, false, false, false, true]);

/* ────────────────────────────────────────────────────────────────
 * 3. Header
 * ──────────────────────────────────────────────────────────────── */
console.log('\n[header]');
const r = AR.parse(TEXT, 'Incident Report - Boone Arkansas.pdf');
eq('reportNumber', r.reportNumber, '26-0417295');
eq('ORI (recovered from a later page header)', r.ar.ori, 'AR0450000');
eq('agencyName', r.agencyName, "Boone County Sheriff's Office");
eq('approvalStatus', r.ar.approvalStatus, 'UNAPPROVED');
eq('reportType carries the approval state', r.reportType, 'Arkansas Incident Report (UNAPPROVED)');
eq('incident date', r.ar.incidentDate, '08/13/2026');
eq('incident time range', r.ar.incidentTime, '15:33 - 16:13');
eq('incident day', r.ar.incidentDay, 'Thursday');
eq('dispatcher', r.ar.dispatcher, 'bmoreau - Moreau, Bianca');
eq('time received', r.ar.timeReceived, '15:40');
eq('time arrived is blank on this report', r.ar.timeArrived, '');
eq('reporting area', r.ar.reportingArea, 'BCSO-Delta');
eq('reporting area is surfaced as beat', r.beat, 'BCSO-Delta');
eq('report date', r.reportDate, '08/13/2026');
eq('report day', r.ar.reportDay, 'Thu');
eq('report time', r.ar.reportTime, '15:33');
eq('reporting officer', r.ar.reportingOfficer, 'DERRICK LANE');
eq('officer code', r.ar.officerCode, 'D0312');
eq('victim name from the page header', r.ar.victimNameHeader, 'HOLLOWAY (JV2), MARISOL');
eq('fromDateTime', r.fromDateTime, '08/13/2026 15:33 - 16:13');
eq('pageCount', r.pageCount, 5);
eq('format tag', r.arFormat, 'ar-incident-report');
eq('format label', r.arFormatLabel, 'Arkansas State NIBRS Incident Report');

/* ────────────────────────────────────────────────────────────────
 * 4. Offense — STATUTE | OFFENSE DESCRIPTION | ADDRESS OF OFFENSE all
 *    collapse onto ONE OCR line with the label row lost entirely.
 * ──────────────────────────────────────────────────────────────── */
console.log('\n[offense]');
eq('one offense', r.offenses.length, 1);
const off = r.offenses[0] || {};
eq('offense number', off.number, '1');
eq('statute', off.statute, '5-14-103a(1)');
eq('description separated from the address', off.description, 'Rape');
eq('address of offense', off.location, '912 THISTLEDOWN LN, Bellefonte, AR 72611');
eq('UCR code', off.ucrCode, '11A');
eq('offense address is surfaced as report location', r.location, '912 THISTLEDOWN LN, Bellefonte, AR 72611');
eq('severity is NOT guessed — this form has no severity field', off.severity, '');
eq('OFFENSE STATUS is a checkbox, so status stays blank', off.status, '');
eq('offense page', off.page, 1);

/* ────────────────────────────────────────────────────────────────
 * 4b. Degraded offense band — the Faulkner report the field reported
 *     as "not parsing" OCR'd the label row as "UCRCODE" with no
 *     "OFFENSE #", and lost the one-digit offense-number column
 *     entirely. The old single "OFFENSE #" anchor therefore skipped
 *     EVERY page, and the report imported with zero offenses and no
 *     address of offense. All values below are REDACTED synthetics
 *     carrying the real OCR damage verbatim.
 * ──────────────────────────────────────────────────────────────── */
console.log('\n[offense — degraded label row]');
const degradedOcr = [
    'ORI NUMBER INTERNAL INCIDENT EXCEPTIONAL',
    'AR0230000 ARKANSAS STATUS: CLEARANCE STATUS:',
    'INCIDENT NUMBER',
    'Z INCIDENT REPORT [J (CA) Closed by Arrest [J (B) Prosecution Declined',
    '26-0905538 UNAPPROVED , ; !',
    'a DATE(S) OF INCIDENT AGENCY NAME',
    '&) 09/18/2026 Faulkner County Sheriff\'s Office (1 Inactive (E) Juvenile, No Custody',
    'Zz, TIME(S) OF INCIDENT DAY(S) OF INCIDENT : (0) Unfounded = N) Not Ap : able',
    'w=i| 19:41 - 23:56 Friday moun pic',
    'DISPATCHER TIME RECEVED TIME ARRIVED | REPORTING AREA EXCEPT. CLEAR. DATE',
    'dbrabham - Brabham, Dixie 19:48 20:07 FCSQ-Delta',
    'UCRCODE | OFFENSE STATUS: OFFENDER USED: [IB (N) Not Applicable Burglary (220) Location 14819: FORCED ENTRY?',
    '13C [J (A Attempted [g (C) Completed | [7] (A) Alcohol [] (C)Cptr. Equip. [J (D) Drugs | # PREMISES ENTERED? [J Yes [J No',
    'STATUTE OFFENSE DESCRIPTION ADDRESS OF OFFENSE',
    '5-13-301a(1a) TERRORISTIC THREATENING - 1ST DEGREE / THRE | 124 JONES RD, CONWAY, AR 72076',
    'LOCATION CODE (Enter 1) [J (47) Liquor Store [] (48) Farm Facility WEAPON FORCE: (Max. 3'
].join('\n');
const rd = AR.parse(degradedOcr, 'degraded.pdf');
eq('degraded band still yields one offense', rd.offenses.length, 1);
const offd = rd.offenses[0] || {};
eq('degraded statute', offd.statute, '5-13-301a(1a)');
eq('degraded description stops at the column pipe', offd.description,
    'TERRORISTIC THREATENING - 1ST DEGREE / THRE');
eq('degraded address of offense', offd.location, '124 JONES RD, CONWAY, AR 72076');
eq('UCR code read without the offense-number column', offd.ucrCode, '13C');
eq('offense number falls back to document order', offd.number, '1');
eq('degraded address surfaced as report location', rd.location, '124 JONES RD, CONWAY, AR 72076');
ok('no "offense row not recognised" warning',
    !rd.diagnostics.warnings.some(w => /No offense row recognised/i.test(w)));

/* quickScan must surface the same two facts to the create-case screen. */
const qsd = AR.quickScan(degradedOcr, 'degraded.pdf');
ok('quickScan matched', qsd.matched === true);
eq('quickScan surfaces ADDRESS OF OFFENSE as location', qsd.location,
    '124 JONES RD, CONWAY, AR 72076');
eq('quickScan primary offense is statute + description, verbatim', qsd.primaryOffense,
    '5-13-301a(1a) TERRORISTIC THREATENING - 1ST DEGREE / THRE');
eq('quickScan offenceList length', qsd.offenseList.length, 1);
ok('quickScan location is a string on a non-Arkansas report',
    typeof AR.quickScan('not an arkansas report', 'x.pdf').location === 'string');
ok('quickScan offenseList is an array on a non-Arkansas report',
    Array.isArray(AR.quickScan('not an arkansas report', 'x.pdf').offenseList));

/* A property row that opens with a three-digit number must never be
 * mistaken for a UCR code — the guard is the OFFENSE STATUS checkbox
 * labels on the same line. */
const propOcr = degradedOcr.replace(
    '13C [J (A Attempted [g (C) Completed | [7] (A) Alcohol [] (C)Cptr. Equip. [J (D) Drugs | # PREMISES ENTERED? [J Yes [J No',
    '520 6 1 RUGER EC9s 9mm Handgun ; SN:00000000 ; MK:RUGER ; 200.00');
const rp = AR.parse(propOcr, 'prop.pdf');
eq('property row is not read as a UCR code', (rp.offenses[0] || {}).ucrCode, '');
eq('the offense row itself still parses', (rp.offenses[0] || {}).statute, '5-13-301a(1a)');

/* ────────────────────────────────────────────────────────────────
 * 5. Persons before recovery
 * ──────────────────────────────────────────────────────────────── */
console.log('\n[persons — layout pass]');
eq('three named persons', r.personsInvolved.length, 3);
eq('roles', r.personsInvolved.map(p => p.involvement),
    ['VICTIM', 'SUSPECT (ARRESTEE/OFFENDER)', 'WITNESS']);

const victim = r.personsInvolved[0];
eq('victim name is verbatim, juvenile alias included', victim.name, 'HOLLOWAY (JV2), MARISOL');
eq('victim alias captured as metadata', victim.alias, 'JV2');
eq('victim DOB', victim.dob, '04/22/2011');
eq('victim exact age', victim.age, '14');
eq('victim resident address', victim.address, '912 THISTLEDOWN LN, Bellefonte, AR 72611');
eq('victim phone, missing paren restored', victim.phone, '(479) 302-6614');
eq('victim source page', victim.sourcePage, 1);

const arrestee = r.personsInvolved[1];
eq('arrestee name verbatim', arrestee.name, 'ABERNATHY (JV1), GRAYSON');
eq('arrestee alias', arrestee.alias, 'JV1');
eq('arrestee exact age', arrestee.age, '14');
eq('arrestee offender number', arrestee.detail, 'Offender #1');
eq('arrestee source page', arrestee.sourcePage, 2);
eq('the page-2 header date is NOT mistaken for the arrestee DOB', arrestee.dob, '');
eq('the blank second arrestee block produces no person',
    r.personsInvolved.filter(p => p.involvement === 'SUSPECT (ARRESTEE/OFFENDER)').length, 1);

const witness = r.personsInvolved[2];
eq('witness name stops before the checkbox junk', witness.name, 'VANDERLINDE (JV3), EMMETT');
eq('witness alias', witness.alias, 'JV3');
eq('witness source page', witness.sourcePage, 4);
eq('the blank second witness block produces no person',
    r.personsInvolved.filter(p => p.involvement === 'WITNESS').length, 1);
eq('the empty COMPLNT block on the property page produces no person',
    r.personsInvolved.filter(p => p.involvement === 'COMPLAINANT').length, 0);

/* ────────────────────────────────────────────────────────────────
 * 6. EVIDENTIARY RULE: nothing derived from a checkbox is ever imported.
 * ──────────────────────────────────────────────────────────────── */
console.log('\n[checkbox fields stay blank]');
r.personsInvolved.concat(r.provisionalPersons).forEach((p, i) => {
    eq('person ' + i + ' sex blank', p.sex, '');
    eq('person ' + i + ' race blank', p.race, '');
    eq('person ' + i + ' ethnicity blank', p.ethnicity, '');
    eq('person ' + i + ' height blank', p.height, '');
    eq('person ' + i + ' weight blank', p.weight, '');
    eq('person ' + i + ' hair blank', p.hair, '');
    eq('person ' + i + ' eyes blank', p.eyes, '');
});
ok('diagnostics record that checkbox fields were skipped', r.diagnostics.checkboxFieldsSkipped === true);
// The fixture has (W) White, (F) Female and (N) Nonhispanic ticked for the
// victim; none of it may leak through under any spelling.
const personDump = JSON.stringify(r.personsInvolved.concat(r.provisionalPersons));
ok('no race value leaked', !/White|Black|Asian|American Indian/i.test(personDump));
ok('no sex value leaked', !/"sex":"(?!")/.test(personDump) && !/Female|"Male"/i.test(personDump));
ok('no ethnicity value leaked', !/Nonhispanic|Hispanic/i.test(personDump));
ok('no residency status leaked', !/Resident|Nonresident/i.test(personDump));

/* ────────────────────────────────────────────────────────────────
 * 7. Provisional persons — a block whose typed NAME the layout OCR pass
 *    dropped must NOT be routed into the case tabs with a blank name.
 * ──────────────────────────────────────────────────────────────── */
console.log('\n[provisional persons]');
eq('two continuation-page blocks held back', r.provisionalPersons.length, 2);
eq('their roles come from the typed headings',
    r.provisionalPersons.map(p => p.involvement), ['CASE WORKER', 'PARENT']);
ok('no provisional person has a name', r.provisionalPersons.every(p => !p.name));
ok('a nameless person never reaches personsInvolved', r.personsInvolved.every(p => !!p.name));
const parentProv = r.provisionalPersons[1];
eq('the PARENT block still yields its address despite a shredded label',
    parentProv.address, '912 THISTLEDOWN LN, Boone County, Bellefonte, AR 72611');
eq('PARENT phone', parentProv.phone, '(479) 318-2270');
eq('PARENT DOB', parentProv.dob, '06/05/1991');
eq('PARENT typed age', parentProv.age, '34');
eq('PARENT detail names the section', parentProv.detail, 'Others Involved — PARENT');
ok('needsNameRecovery is true', AR.needsNameRecovery(r) === true);
eq('recovery targets page 5 only', AR.nameRecoveryPages(r), [5]);
ok('a warning names the affected blocks',
    r.diagnostics.warnings.some(w => /CASE WORKER \(page 5\)/.test(w) && /PARENT \(page 5\)/.test(w)));

/* ────────────────────────────────────────────────────────────────
 * 8. Narrative
 * ──────────────────────────────────────────────────────────────── */
console.log('\n[narrative]');
eq('one narrative', r.narratives.length, 1);
const nar = r.narratives[0] || {};
ok('officer is a string (renderRmsImportTab calls officer.split)', typeof nar.officer === 'string');
ok('badge is a string', typeof nar.badge === 'string');
eq('officer is the name only, code goes to badge', nar.officer, 'DERRICK LANE');
eq('badge', nar.badge, 'D0312');
ok('narrative opens with the dispatch paragraph',
    /^On Thursday, August 13, 2026 at approximately 1545 hours/.test(nar.text), nar.text.slice(0, 60));
ok('narrative keeps the ASP case number', /ASP Case number is 318-4407/.test(nar.text));
ok('narrative keeps the closing paragraph',
    /There is a lot of blanks throughout this report/.test(nar.text));
ok('narrative excludes the CONTINUATION PAGE marker', !/CONTINUATION PAGE/.test(nar.text));
ok('narrative excludes page header rows', !/26-0417295/.test(nar.text));
ok('narrative excludes the form label itself', !/^NARRATIVE:/m.test(nar.text));
ok('narrative is not truncated', nar.text.length > 1200, nar.text.length);
ok('OCR damage is preserved, not "corrected"', /IT called and made contact/.test(nar.text));

/* Paragraph reconstruction. The printed form separates paragraphs with a blank
 * ruled row that the OCR does not emit, so without this the narrative imported
 * as one undifferentiated wall of text. Printed line breaks are kept verbatim;
 * the ONLY thing added is a blank line at a sentence boundary. */
console.log('\n[narrative paragraphs]');
const paras = nar.text.split('\n\n');
eq('the layout pass yields 6 paragraphs (one closing line was dropped by OCR)', paras.length, 6);
ok('paragraph 1 break lands after "...advocate."',
    /advocate\.$/.test(paras[0]), paras[0].slice(-30));
ok('paragraph break after "have an exact date/time."',
    paras.some(p => /have an exact date\/time\.$/.test(p)));
ok('the ASP case number is its own paragraph',
    paras.some(p => /^ASP Case number is 318-4407 .* report number\.$/.test(p)));
ok('no paragraph is empty', paras.every(p => p.trim().length > 0));
ok('no run of three or more newlines', !/\n{3}/.test(nar.text));
ok('printed line breaks inside a paragraph are preserved',
    /call for service\nwith ASP Crimes/.test(nar.text));
ok('no line was joined across a paragraph boundary',
    !/advocate\. IT called/.test(nar.text));

const P = AR._internal.paragraphize;
eq('paragraphize keeps a single line untouched', P(['Only one line.']), 'Only one line.');
eq('paragraphize does not break a wrapped line that ends mid-sentence',
    P(['first part of a', 'sentence.']), 'first part of a\nsentence.');
eq('paragraphize breaks at a sentence boundary',
    P(['Done here.', 'New thought.']), 'Done here.\n\nNew thought.');
eq('paragraphize does NOT break after a title abbreviation',
    P(['I spoke with Ms.', 'Marchetti about it.']), 'I spoke with Ms.\nMarchetti about it.');
eq('paragraphize does NOT break after a single initial',
    P(['The reporting officer was J.', 'Smith of the agency.']),
    'The reporting officer was J.\nSmith of the agency.');
eq('paragraphize does NOT break when the next line is lower case',
    P(['ends with a period.', 'continues in lower case']),
    'ends with a period.\ncontinues in lower case');
eq('paragraphize handles an empty list', P([]), '');

/* ────────────────────────────────────────────────────────────────
 * 8b. NARRATIVE LINE RECOVERY.
 *     tesseract.js defaults to PSM 6, which silently drops the short trailing
 *     row of a paragraph. PSM 3 reads those rows but scrambles the surrounding
 *     column order, so the merge must be additive and anchored.
 * ──────────────────────────────────────────────────────────────── */
console.log('\n[narrative recovery]');
const PSM3_P4 = loadFixture('ar-incident-report.page4-psm3.txt');

eq('narrativeRecoveryPages points at the narrative page', AR.narrativeRecoveryPages(r), [4]);
eq('narrativeRecoveryPages on a foreign object is empty', AR.narrativeRecoveryPages({}), []);
eq('narrativeRecoveryPages on null is empty', AR.narrativeRecoveryPages(null), []);

ok('the primary pass really is missing the dropped lines',
    !/with it\./.test(nar.text) && !/could obtain/.test(nar.text));

const rN = AR.parse(TEXT, 'x.pdf');
eq('recoverNarrative with no alt text is a no-op', AR.recoverNarrative(rN, null), 0);
eq('recoverNarrative with an empty page map is a no-op', AR.recoverNarrative(rN, {}), 0);
eq('recoverNarrative recovers exactly the two dropped lines',
    AR.recoverNarrative(rN, { '4': PSM3_P4 }), 2);
const nt = rN.narratives[0].text;
ok('"with it." is restored', /with it\./.test(nt));
ok('"provided or I could obtain." is restored', /provided or I could obtain\./.test(nt));
ok('"with it." is restored in the RIGHT place',
    /he was suffering\nwith it\.\n\nJV3 said/.test(nt), nt);
ok('the closing line is restored at the end',
    /information that was\nprovided or I could obtain\.$/.test(nt.trim()));
eq('the recovered narrative has all 7 printed paragraphs', nt.split('\n\n').length, 7);
eq('diagnostics count the recovered lines', rN.diagnostics.narrativeLinesRecovered, 2);
eq('diagnostics.narrativeChars is refreshed', rN.diagnostics.narrativeChars, nt.length);
ok('the recovery is disclosed in diagnostics.warnings',
    rN.diagnostics.warnings.some(w => /^Narrative: 2 lines missed by the primary OCR pass/.test(w)),
    rN.diagnostics.warnings);
eq('recovery is idempotent', AR.recoverNarrative(rN, { '4': PSM3_P4 }), 0);

// The PSM 3 pass interleaves form furniture into the middle of the narrative.
// None of it may survive the merge.
ok('form furniture is not merged in', !/PAGE #|INCIDENT NUMBER|DEEZ/.test(nt), nt);
ok('the bare "NAME:" label is not merged in', !/^NAME:/m.test(nt));
ok('the page header incident number is not merged in', !/26-0417295/.test(nt));
ok('a stray single word from a scrambled wrap is not merged in',
    !/^Marchetti$/m.test(nt) && !/^First,$/m.test(nt));
ok('no line is duplicated', (function () {
    const seen = {};
    return nt.split('\n').filter(Boolean).every(l => {
        const k = l.trim();
        if (seen[k]) return false;
        seen[k] = true;
        return true;
    });
})());

// An unanchored fragment (nothing before it matches the primary narrative)
// must be discarded rather than prepended.
const rU = AR.parse(TEXT, 'x.pdf');
eq('an unanchored fragment is discarded',
    AR.recoverNarrative(rU, { '4': 'Some entirely unrelated prose line that ends here.' }), 0);

// A report with no narrative at all must not throw.
eq('recoverNarrative on a narrative-less report is a no-op',
    AR.recoverNarrative({ narratives: [] }, { '4': PSM3_P4 }), 0);
eq('recoverNarrative on null is a no-op', AR.recoverNarrative(null, { '4': PSM3_P4 }), 0);

const F = AR._internal.isNarrativeFragment;
console.log('\n[_isNarrativeFragment]');
ok('accepts a short two-word closing line', F('with it.') === true);
ok('accepts a five-word closing line', F('provided or I could obtain.') === true);
ok('accepts a full prose row',
    F('JV3 said the mistake was raping his ex-girlfriend, however') === true);
ok('rejects a single word', F('Marchetti') === false);
ok('rejects a one-word fragment with a comma', F('First,') === false);
ok('rejects an all-caps form label', F('INCIDENT NUMBER') === false);
ok('rejects the PAGE # label', F('PAGE #') === false);
ok('rejects OCR garbage', F('DEEZ ==') === false);
ok('rejects a checkbox row', F('[J (U) Unk. [1 (W) White [7 (B) Black') === false);
ok('rejects a bare number', F('26-0417295') === false);
ok('rejects empty', F('') === false);
ok('rejects null', F(null) === false);
ok('rejects a two-word fragment with no sentence end', F('older brother') === false);

/* ────────────────────────────────────────────────────────────────
 * 9. THE ROUTING CONTRACT.
 *    These filters are copied verbatim from routeRmsPersonsToTabs in
 *    case-detail-with-analytics.html. If that function ever changes, this
 *    block fails and tells us the involvement vocabulary must move with it.
 *    Note the suspect filter does NOT match "ARRESTEE" or "OFFENDER" — which
 *    is exactly why the parser emits "SUSPECT (ARRESTEE/OFFENDER)".
 * ──────────────────────────────────────────────────────────────── */
console.log('\n[routing contract]');
function route(persons) {
    const inv = p => p.involvement || '';
    const matchedRoles = /SUSPECT|ARRESTED|DEFENDANT|WITNESS/i;
    return {
        suspects: persons.filter(p => /SUSPECT|ARRESTED|DEFENDANT/i.test(inv(p))),
        victims: persons.filter(p => /VICTIM/i.test(inv(p)) && !/VICTIM'S|PARENT|GUARDIAN/i.test(inv(p))),
        witnesses: persons.filter(p => /WITNESS/i.test(inv(p))),
        involved: persons.filter(p => {
            const i = inv(p);
            if (/REPORTING\s*PARTY|INFORMANT|PARENT|GUARDIAN/i.test(i)) return true;
            if (/VICTIM/i.test(i) && !/PARENT|GUARDIAN/i.test(i)) return false;
            if (matchedRoles.test(i)) return false;
            return true;
        })
    };
}
const preRoute = route(r.personsInvolved);
eq('victim routes to Victims', preRoute.victims.map(p => p.name), ['HOLLOWAY (JV2), MARISOL']);
eq('arrestee routes to Suspects (NOT Involved Persons)',
    preRoute.suspects.map(p => p.name), ['ABERNATHY (JV1), GRAYSON']);
eq('witness routes to Witnesses', preRoute.witnesses.map(p => p.name), ['VANDERLINDE (JV3), EMMETT']);
eq('nothing spills into Involved Persons yet', preRoute.involved.map(p => p.name), []);
ok('every person lands in exactly one tab', r.personsInvolved.every(p => {
    const one = route([p]);
    return one.suspects.length + one.victims.length + one.witnesses.length + one.involved.length === 1;
}));

/* ────────────────────────────────────────────────────────────────
 * 10. recoverNames() — sparse-text OCR of page 5 supplies the two names
 *     the layout pass dropped, and they are promoted into the case.
 * ──────────────────────────────────────────────────────────────── */
console.log('\n[name recovery]');
eq('no-op without sparse text', AR.recoverNames(r, null), 0);
eq('no-op when the needed page is absent', AR.recoverNames(r, { 3: 'nothing here' }), 0);
eq('two names recovered', AR.recoverNames(r, { 5: SPARSE5 }), 2);
eq('now five persons', r.personsInvolved.length, 5);
eq('nothing left provisional', r.provisionalPersons.length, 0);
ok('needsNameRecovery is now false', AR.needsNameRecovery(r) === false);

const caseWorker = r.personsInvolved.find(p => p.involvement === 'CASE WORKER');
const parent = r.personsInvolved.find(p => p.involvement === 'PARENT');
eq('CASE WORKER name, verbatim including the agency suffix',
    caseWorker && caseWorker.name, 'QUILLEN, DELPHINE ASP CAC');
eq('PARENT name, verbatim mixed case', parent && parent.name, 'Marchetti, Rowena Claire');
ok('the recovery is disclosed in the record',
    /Name read by sparse-text OCR of page 5/.test(caseWorker.comments));
eq('recovery does not disturb values the layout pass read',
    parent.address, '912 THISTLEDOWN LN, Boone County, Bellefonte, AR 72611');
eq('PARENT phone survives recovery', parent.phone, '(479) 318-2270');
eq('the CASE WORKER does NOT inherit the PARENT address', caseWorker.address, '');
eq('the CASE WORKER does NOT inherit the PARENT phone', caseWorker.phone, '');
eq('the CASE WORKER does NOT inherit the PARENT DOB', caseWorker.dob, '');
ok('no block inherits the victim name from the page-header row',
    r.personsInvolved.filter(p => p.name === 'HOLLOWAY (JV2), MARISOL').length === 1);
eq('recovered count is recorded', r.diagnostics.namesRecovered, 2);
ok('the missing-name warning is withdrawn once the names are read',
    !r.diagnostics.warnings.some(w => /^Name not read for/.test(w)), r.diagnostics.warnings);
ok('recovery is idempotent', AR.recoverNames(r, { 5: SPARSE5 }) === 0);

const postRoute = route(r.personsInvolved);
eq('CASE WORKER routes to Involved Persons', postRoute.involved.map(p => p.involvement).sort(),
    ['CASE WORKER', 'PARENT']);
eq('recovery adds nobody to Suspects', postRoute.suspects.length, 1);
eq('recovery adds nobody to Victims', postRoute.victims.length, 1);
eq('recovery adds nobody to Witnesses', postRoute.witnesses.length, 1);

/* ────────────────────────────────────────────────────────────────
 * 11. quickScan() — the create-case screen path in index.html
 * ──────────────────────────────────────────────────────────────── */
console.log('\n[quickScan]');
const qs = AR.quickScan(TEXT, 'Incident Report - Boone Arkansas.pdf');
ok('matched', qs.matched === true);
eq('case number for the create-case form', qs.caseNum, '26-0417295');
ok('synopsis mentions the statute', /5-14-103a\(1\)/.test(qs.synopsis), qs.synopsis);
ok('synopsis mentions the offense', /Rape/.test(qs.synopsis));
ok('synopsis mentions the occurrence date', /Occurred 08\/13\/2026/.test(qs.synopsis));
ok('synopsis mentions the agency', /Boone County Sheriff's Office/.test(qs.synopsis));
ok('synopsis has no double punctuation', !/\.\s+at\s/.test(qs.synopsis) && !/\.\./.test(qs.synopsis));
eq('ticks rmsImports', qs.detected.rmsImports, true);
eq('ticks victims', qs.detected.victims, true);
eq('ticks suspects', qs.detected.suspects, true);
eq('ticks witnesses', qs.detected.witnesses, true);
eq('ticks involvedPersons (the PARENT block has data)', qs.detected.involvedPersons, true);
eq('does not tick vehicles — the VEHICLE band is empty', qs.detected.vehicles, undefined);
const qsMiss = AR.quickScan('some other RMS report', 'x.pdf');
ok('quickScan is inert on a non-Arkansas report', qsMiss.matched === false);
eq('inert quickScan yields no case number', qsMiss.caseNum, '');
eq('inert quickScan yields no module flags', qsMiss.detected, {});

/* ────────────────────────────────────────────────────────────────
 * 12. Shared-UI shape contract
 * ──────────────────────────────────────────────────────────────── */
console.log('\n[report shape]');
['id', 'fileName', 'importedAt', 'reportNumber', 'reportDate', 'reportType', 'supplementNo',
 'agencyName', 'location', 'beat', 'fromDateTime', 'toDateTime', 'rawText']
    .forEach(k => ok('"' + k + '" is a string', typeof r[k] === 'string', { key: k, got: r[k] }));
['offenses', 'personsInvolved', 'vehicles', 'property', 'narratives', 'digital',
 'confidentialPersons', 'provisionalPersons']
    .forEach(k => ok('"' + k + '" is an array', Array.isArray(r[k]), { key: k, got: r[k] }));
ok('id is prefixed rms_ like every other RMS report', /^rms_/.test(r.id));
ok('importedAt is an ISO timestamp', !isNaN(Date.parse(r.importedAt)));
ok('rawText is retained for re-parsing', r.rawText.length > 10000, r.rawText.length);
ok('every person carries a non-empty involvement string',
    r.personsInvolved.every(p => typeof p.involvement === 'string' && p.involvement.length > 0));
ok('every offense carries a string statute',
    r.offenses.every(o => typeof o.statute === 'string'));

/* ────────────────────────────────────────────────────────────────
 * 13. _extractName() — the workhorse. Names share OCR lines with
 *     checkbox glyphs, dates and column labels.
 * ──────────────────────────────────────────────────────────────── */
console.log('\n[_extractName]');
const xn = AR._internal.extractName;
eq('trailing DOB is not absorbed',
    xn('1 HOLLOWAY (JV2), MARISOL 04/22/2011'), 'HOLLOWAY (JV2), MARISOL');
eq('gutter noise is stripped', xn('= ABERNATHY (JV1), GRAYSON'), 'ABERNATHY (JV1), GRAYSON');
eq('checkbox junk after the name is dropped',
    xn('VANDERLINDE (JV3), EMMETT £5 (F) Female OJ 0) Unknown | = 1 american Indian'),
    'VANDERLINDE (JV3), EMMETT');
eq('a typed agency suffix in the middle-name field is kept',
    xn('QUILLEN, DELPHINE ASP CAC'), 'QUILLEN, DELPHINE ASP CAC');
eq('mixed-case names work', xn('Marchetti, Rowena Claire'), 'Marchetti, Rowena Claire');
eq('two-letter checkbox glyphs are not absorbed as a middle name',
    xn('Marchetti, Rowena Claire IH (F) Female Bl (W) White'), 'Marchetti, Rowena Claire');
eq('a street address is not a name', xn('912 THISTLEDOWN LN, Bellefonte, AR 72611'), null);
eq('an address with no ZIP is not a name', xn('912 THISTLEDOWN LN, Boone County, Bellefonte, AR'), null);
eq('the NAME label row is not a name',
    xn("VICTIM # NAME: Last, First, Middle SOC. SEC. NO. DRIVER'S LICENSE DR. LI. STATE | DATE OF BIRTH"), null);
eq('the bare NAME label is not a name', xn('NAME: Last, First, Middle SEX: -'), null);
eq('a line with no comma is not a name', xn('RESIDENT ADDRESS: Street City State Zip'), null);
eq('pure OCR garbage is not a name', xn('a ici itis A'), null);
eq('empty string', xn(''), null);
eq('null input', xn(null), null);
eq('an initial with a period is kept', xn('DOE, JOHN Q.'), 'DOE, JOHN Q.');
eq('a hyphenated surname works', xn('SMITH-JONES, ALICE'), 'SMITH-JONES, ALICE');
eq('an apostrophe surname works', xn("O'BRIEN, SEAN"), "O'BRIEN, SEAN");
eq('a two-part surname works', xn('VAN DYKE, MARY'), 'VAN DYKE, MARY');

/* ────────────────────────────────────────────────────────────────
 * 14. Small helpers
 * ──────────────────────────────────────────────────────────────── */
console.log('\n[helpers]');
const fp = AR._internal.fmtPhone;
eq('restores the paren the scan lost', fp('479) 302-6614 Qoooo (G8 Spouse'), '(479) 302-6614');
eq('normalises a complete number', fp('(479) 318-2270 [1 (U) Unknown'), '(479) 318-2270');
eq('accepts a dotted number', fp('479.318.2270'), '(479) 318-2270');
eq('a date is not a phone number', fp('04/22/2011'), '');
eq('NIBRS relationship column numbers are not a phone',
    fp('#MOH2 #3 #4 #5 #6 #7 #8 #9 #10 VICTIM WAS:'), '');
eq('an age range is not a phone', fp('(99) Over 98 Yrs. Old (BB) 7-364 Days Old'), '');
eq('no phone on an empty line', fp(''), '');

const pr = AR._internal.isProse;
ok('narrative text is prose', pr('On Thursday, August 13, 2026 at approximately 1545 hours, I was dispatched to a call for service') === true);
ok('a checkbox grid is not prose', pr('[J (05) Commercial/Office Building [J (23) Service/Gas Station [J (50) Park/Playground') === false);
ok('an all-caps label row is not prose', pr('RESIDENT ADDRESS: STREET CITY STATE ZIP RESIDENT PHONE EMPLOYMENT PHONE') === false);
ok('a short line is not prose', pr('CASE WORKER') === false);

/* ────────────────────────────────────────────────────────────────
 * 14b. Banded narrative rebuild — glyph stripping and page selection.
 *      Both gates below were written against real failures on the
 *      Faulkner report and both protect EVIDENCE, so they are pinned.
 * ──────────────────────────────────────────────────────────────── */
console.log('\n[banded narrative]');
const strip = AR._internal.stripRuleGlyphs;
eq('leading rule pipe is stripped',
    strip('| Upon arrival, I made contact with Ms Stivers.'),
    'Upon arrival, I made contact with Ms Stivers.');
eq('trailing rule pipe is stripped',
    strip('...in an area near his mother\u2019s |'),
    '...in an area near his mother\u2019s');
eq('both margins at once',
    strip('| Jones Rd. Still, Ms Miracle Stivers had taken her kids to 122 Jones Rd., |'),
    'Jones Rd. Still, Ms Miracle Stivers had taken her kids to 122 Jones Rd.,');
/* "I " is a real line start in a police narrative and must survive. */
eq('a line that genuinely starts with I is untouched',
    strip('I went outside to gather a Lethality Screening Assessment.'),
    'I went outside to gather a Lethality Screening Assessment.');
/* The regression that forced the narrow rule: a wrapped line ending on
 * the first word of the next sentence. Deleting it loses evidence. */
eq('a real trailing word after a period is NEVER deleted',
    strip('...and brought it back to Ms Stivers. Ms'),
    '...and brought it back to Ms Stivers. Ms');
eq('a trailing single letter is left visible rather than guessed at',
    strip('...he pushed her and threw her phone on the ground. Ms i'),
    '...he pushed her and threw her phone on the ground. Ms i');
eq('strip is inert on empty input', strip(''), '');
eq('strip is inert on null', strip(null), '');

/* Prose must DOMINATE an unlabelled page before its text joins the
 * narrative. A NIBRS legend page reads as a dozen prose-shaped lines
 * among sixty of checkbox furniture, and it used to be appended whole. */
const junkPage = [
    'CONTINUATION PAGE',
    '09/18/2026 | 26-0905538 AR0230000 | BRANDON WHITFIELD F4388',
    'NARRATIVE:',
    'On 09/18/2026 at approximately 1948 hours, I was dispatched to a domestic disturbance at 124 Jones',
    'Rd. Before I arrived, I was advised by my emergency operations that the incident occurred at 306',
    'Jones Rd. Still, the victim had taken her kids to another residence for safety.',
    'CONTINUATION PAGE',
    '09/18/2026 | 26-0905538 AR0230000 | BRANDON WHITFIELD F4388',
    '801 LOCUST ST, CONWAY, AR 72034 (check relationship under appropriate offender number):',
    'Aggravated Assault/Murder: (max. 2) Negligent Manslaughter: (enter 1) (RU) Relationship Unknown',
    '(01) Argument (30) Child Playing With Weapon afin] ] C1 (ST) Stranger',
    '[ (14) HoteliMotelEtc. LC] (41) Auto Dealership New/Used I (40) Personal Weapons (Hands, etc.)',
    '[J (02) Bank/Savings & Loan [1 (19) Rental/Storage Facility Track',
    '[J (03) Bar/Night Club [l (20) Residence/Home [7 (48) Industrial Site',
    '[1 (04) Church/Synagogue/Temple/Mosque [7] (21) Restaurant [3 (49) Military Installation',
    '[J (05) Commercial/Office Building [C1 (23) Service/Gas Station [1 (50) Park/Playground'
].join('\n');
const rj = AR.parse('INCIDENT REPORT\n' + junkPage, 'junk.pdf');
const njt = (rj.narratives[0] || {}).text || '';
ok('the labelled narrative page is kept', /dispatched to a domestic disturbance/.test(njt));
ok('the NIBRS relationship legend does NOT reach the narrative',
    !/Relationship Unknown/.test(njt), njt.slice(-200));
ok('the location-code legend does NOT reach the narrative',
    !/Auto Dealership/.test(njt), njt.slice(-200));
ok('the form address line does NOT reach the narrative',
    !/check relationship under appropriate offender number/.test(njt), njt.slice(-200));

/* ...but the rejected page must still be OFFERED to the banded re-read,
 * or a narrative that ran onto it is lost outright. */
const bandPages = AR.narrativeBandPages(rj);
ok('narrativeBandPages returns an array', Array.isArray(bandPages));
ok('the narrative page is offered to the banded re-read', bandPages.indexOf(1) !== -1, bandPages);
ok('the rejected continuation page is still offered', bandPages.indexOf(2) !== -1, bandPages);
ok('narrativeBandPages is safe on a report with no narrative',
    Array.isArray(AR.narrativeBandPages(AR.parse('INCIDENT REPORT', 'x.pdf'))));
ok('narrativeBandPages is safe on a non-report', Array.isArray(AR.narrativeBandPages(null)));
eq('recoverNarrativeBanded replaces nothing when handed nothing',
    AR.recoverNarrativeBanded(rj, {}), 0);
eq('recoverNarrativeBanded is safe on null', AR.recoverNarrativeBanded(null, null), 0);

/* ────────────────────────────────────────────────────────────────
 * 15. Degrade, never throw — a half-understood report must import
 *     "successfully" with diagnostics, not crash the importer.
 * ──────────────────────────────────────────────────────────────── */
console.log('\n[degradation]');
[
    ['empty string', ''],
    ['null', null],
    ['undefined', undefined],
    ['title only', 'INCIDENT REPORT'],
    ['title plus noise', 'INCIDENT REPORT\n[J [1 O LJ Il IE Bl\n\n\n'],
    ['header row only', '08/13/2026 | 26-0417295 AR0450000 | DERRICK LANE D0312'],
    ['first page only', TEXT.split('\n').slice(0, 80).join('\n')],
    ['continuation page only', TEXT.split('\n').slice(230).join('\n')],
    ['narrative page only', TEXT.split('\n').slice(196, 230).join('\n')],
    ['CRLF line endings', TEXT.replace(/\n/g, '\r\n')],
    ['every line reversed', TEXT.split('\n').reverse().join('\n')]
].forEach(([label, input]) => {
    let out = null, threw = null;
    try { out = AR.parse(input, 'x.pdf'); } catch (e) { threw = e; }
    ok('parse survives: ' + label, !threw, threw && threw.message);
    if (out) {
        ok('  ...returns arrays: ' + label,
            Array.isArray(out.offenses) && Array.isArray(out.personsInvolved) &&
            Array.isArray(out.narratives) && Array.isArray(out.provisionalPersons));
        ok('  ...involvement is always a string: ' + label,
            out.personsInvolved.every(p => typeof p.involvement === 'string'));
        ok('  ...narrative officer is always a string: ' + label,
            out.narratives.every(n => typeof n.officer === 'string'));
    }
    let qsOut = null;
    try { qsOut = AR.quickScan(input, 'x.pdf'); } catch (e) { qsOut = null; threw = e; }
    ok('quickScan survives: ' + label, !!qsOut);
});
// CRLF must be a no-op, not a different parse.
const crlf = AR.parse(TEXT.replace(/\n/g, '\r\n'), 'x.pdf');
eq('CRLF yields the same person count', crlf.personsInvolved.length, 3);
eq('CRLF yields the same report number', crlf.reportNumber, '26-0417295');
ok('a report with nothing readable still records warnings',
    AR.parse('INCIDENT REPORT', 'x.pdf').diagnostics.warnings.length > 0);

/* ────────────────────────────────────────────────────────────────
 * 16. The junk gate — OCR wreckage is NOT the officer's narrative.
 *
 *     A field officer photographed a VIPER case whose Officer Narratives
 *     card rendered 22 rows of "a e———  /  ee — eee AB  /  Ee en". The
 *     labelled-NARRATIVE branch had accepted every non-empty line on
 *     trust. Rendering noise as evidence is worse than rendering nothing.
 * ──────────────────────────────────────────────────────────────── */
console.log('\n[junk gate]');
const WRECK = [
    'INCIDENT REPORT',
    '09/18/2026 | 26-0905538 AR0230000 | BRANDON WHITFIELD F4388',
    'NARRATIVE:',
    'a e———', 'ee — eee AB', 'Le————eerie', 'Ee en', 'ee———|', 'a————',
    'ee —', 'ES——', 'rr——', 'ee ee r——', 'Ce—————', '—————', 'A a——',
    'oe — me', '——', '[a————l', 'eae', 'ee————', 'EO —', 'Fo ————'
].join('\n');
const rw = AR.parse(WRECK, 'wreck.pdf');
eq('an unreadable narrative page yields NO narrative', rw.narratives.length, 0);
ok('the wreckage never reaches a narrative',
    !JSON.stringify(rw.narratives).includes('Le'), rw.narratives);
ok('the withheld page is named in a warning',
    rw.diagnostics.warnings.some(w => /^Narrative text on page\(s\) 1\b/.test(w)),
    rw.diagnostics.warnings);
eq('the withheld page is recorded', rw.narrativeRecovery.unreadablePages, [1]);
ok('the withheld page is offered to the banded re-read',
    AR.narrativeBandPages(rw).indexOf(1) !== -1, AR.narrativeBandPages(rw));

// A terse but READABLE narrative is not wreckage.
const terse = AR.parse([
    'INCIDENT REPORT',
    '09/18/2026 | 26-0905538 AR0230000 | BRANDON WHITFIELD F4388',
    'NARRATIVE:',
    'I responded to the address and made contact with the complainant.',
    'No further action was taken at this time.'
].join('\n'), 'terse.pdf');
eq('a short readable narrative is kept', terse.narratives.length, 1);
eq('no unreadable pages are claimed', terse.narrativeRecovery.unreadablePages, []);

const bir = AR._internal.bodyIsReadable;
ok('bodyIsReadable rejects pure wreckage', bir(['A', 'ER', 'EE', '-—', 'Ce ——']) === false);
ok('bodyIsReadable accepts two prose lines',
    bir(['I made contact with the complainant at the residence.',
         'She advised that the suspect had left on foot.']) === true);
ok('bodyIsReadable accepts a single-line narrative',
    bir(['I collected the evidence and placed it into the property room.']) === true);
ok('bodyIsReadable is safe on an empty body', bir([]) === false);

/* A banded rebuild must clear the warning it just made untrue. */
const rw2 = AR.parse(WRECK, 'wreck.pdf');
const rebuilt = AR.recoverNarrativeBanded(rw2, {
    1: {
        lines: [
            { conf: 90, text: 'I was dispatched to a disturbance at 124 Jones Rd. and made contact' },
            { conf: 91, text: 'with the complainant, who advised the suspect had left on foot before' },
            { conf: 88, text: 'my arrival. I documented the damage to the front door and cleared.' }
        ]
    }
});
eq('the banded re-read rebuilds the page', rebuilt, 1);
ok('the stale unreadable warning is dropped',
    !rw2.diagnostics.warnings.some(w => /^Narrative text on page\(s\)/.test(w)),
    rw2.diagnostics.warnings);
ok('the "No NARRATIVE section found" warning is dropped too',
    !rw2.diagnostics.warnings.includes('No NARRATIVE section found.'),
    rw2.diagnostics.warnings);
eq('nothing is still listed as unreadable', rw2.narrativeRecovery.unreadablePages, []);
ok('the rebuild is disclosed',
    rw2.diagnostics.warnings.some(w => /re-read row by row/.test(w)), rw2.diagnostics.warnings);

/* A rebuilt narrative must still carry the REPORTING OFFICER.
 *
 * When the primary pass finds no narrative at all, parse() has no narrative
 * item to stamp the officer onto, so the item created by the banded rebuild
 * was rendering in the case file as "Unknown Officer" — an officer's own
 * narrative, unattributed. The name is printed in the page header band and
 * was already read at parse time. */
eq('the header officer was read', rw2.ar.reportingOfficer, 'BRANDON WHITFIELD');
eq('a rebuilt narrative is attributed to the reporting officer',
    rw2.narratives[0].officer, 'BRANDON WHITFIELD');
eq('a rebuilt narrative carries the officer code', rw2.narratives[0].badge, 'F4388');
ok('the rebuilt narrative officer is a string (UI invariant)',
    rw2.narratives.every(n => typeof n.officer === 'string' && typeof n.badge === 'string'));

/* ────────────────────────────────────────────────────────────────
 * 17. Banded / primary row reconciliation.
 *
 *     Band OCR shares its first band with the form's "NARRATIVE:" cell
 *     label, which wrecks the words beside it — while the primary pass,
 *     though it collapsed on the PAGE, read that ROW correctly. Measured
 *     on Faulkner 26-0506420 page 4: the banded row lost the dispatch
 *     date, which is evidence.
 * ──────────────────────────────────────────────────────────────── */
console.log('\n[reconcile]');
const rec = AR._internal.reconcileBandedWithPrimary;
const banded1 = ['rg SN at ——— 2309, T was dispatched to 48 Brown Rd. in regards to a sexual Ri'];
const primary1 = ['On 05/22/2026 at approximately 2309, I was dispatched to 48 Brown Rd. in regards to a sexual'];
eq('a wrecked banded row loses to the clean primary row',
    rec(banded1, primary1), primary1);
eq('a clean banded row survives a wrecked primary row',
    rec(primary1, banded1), primary1);
eq('an unmatched banded row is left alone',
    rec(['He stated that he had been drinking earlier in the evening.'],
        ['The vehicle was towed from the scene by a licensed operator.']),
    ['He stated that he had been drinking earlier in the evening.']);
eq('a short banded row is never substituted', rec(['Rd.'], primary1), ['Rd.']);
eq('no primary lines is a no-op', rec(banded1, null), banded1);
eq('an empty primary page is a no-op', rec(banded1, []), banded1);
// One primary row may not be spent twice, or a repeated wrap duplicates it.
const twice = rec(banded1.concat(banded1), primary1);
eq('a primary row is spent at most once', twice[1], banded1[0]);

const lq = AR._internal.lineQuality;
ok('lineQuality scores prose above debris',
    lq('I was dispatched to 48 Brown Rd. in regards to a sexual') >
    lq('rg SN at ——— 2309, T was Ri'));

/* ────────────────────────────────────────────────────────────────
 * 18. The SUPPLEMENT NARRATIVE form — a SECOND Arkansas form.
 *
 *     Follow-up work (evidence collection, later interviews, transports)
 *     arrives on its own one-page form carrying the parent incident
 *     number and nothing but a narrative. Three of the four reference
 *     documents for one incident were supplements, and before this branch
 *     existed detect() returned false for every one of them.
 * ──────────────────────────────────────────────────────────────── */
console.log('\n[supplement]');
const SUPP = loadFixture('ar-supplement-narrative.ocr.txt');
const SUPP_WRECKED = loadFixture('ar-supplement-narrative.wrecked.txt');

ok('detects the supplement form', AR.detect(SUPP) === true);
ok('a bare title is not a supplement', AR.detect('SUPPLEMENT NARRATIVE') === false);
ok('a supplement needs an incident number',
    AR.detect('SUPPLEMENT NARRATIVE\nINCIDENT NUMBER\nSUPPLEMENTING OFFICER\n') === false);
ok('another agency\'s supplement wording is not claimed',
    AR.detect('Supplement No: 1\nNarrative\nGenerated By: jdoe') === false);

const rs = AR.parse(SUPP, 'Report 2 Sup 4.pdf');
eq('arFormat', rs.arFormat, 'ar-supplement-narrative');
eq('the parent incident number', rs.reportNumber, '26-0512833');
eq('the supplement number', rs.supplementNo, '4');
eq('reportDate is the supplement date', rs.reportDate, '06/12/2026');
eq('incident date/time', rs.fromDateTime, '06/11/2026 21:40');
eq('supplement type', rs.ar.supplementType, 'ADDITIONAL INFORMATION');
eq('supplement time', rs.ar.supplementTime, '8:14');
eq('reportType names the form and the type', rs.reportType,
    'Arkansas Supplement Narrative (ADDITIONAL INFORMATION)');
eq('one narrative', rs.narratives.length, 1);
eq('the supplementing officer', rs.narratives[0].officer, 'RANDALL PIKE');
eq('the officer code lands in badge', rs.narratives[0].badge, 'F4102');
ok('the narrative opens with the officer\'s first line',
    /^On June 12, 2026 at approximately 0755 hours/.test(rs.narratives[0].text),
    rs.narratives[0].text.slice(0, 80));
ok('the narrative carries the seizure', /folding knife/.test(rs.narratives[0].text));
ok('the form header never reaches the narrative',
    !/SUPPLEMENT (TYPE|DATE)|INCIDENT NUMBER|NARRATIVE:/.test(rs.narratives[0].text),
    rs.narratives[0].text);
eq('a supplement routes no persons', rs.personsInvolved.length, 0);
eq('a supplement claims no offenses', rs.offenses.length, 0);
eq('a supplement claims no location', rs.location, '');
ok('narrative officer is a string', typeof rs.narratives[0].officer === 'string');
eq('page 1 is offered to both recovery passes', AR.narrativeBandPages(rs), [1]);
eq('page 1 is offered to the PSM 3 pass', AR.narrativeRecoveryPages(rs), [1]);
ok('nameRecovery is present and empty', AR.needsNameRecovery(rs) === false);

const qsSupp = AR.quickScan(SUPP, 'Report 2 Sup 4.pdf');
ok('quickScan matches the supplement', qsSupp.matched === true);
eq('quickScan returns the parent case number', qsSupp.caseNum, '26-0512833');
ok('quickScan ticks the RMS module', qsSupp.detected.rmsImports === true);
ok('quickScan names the supplementing officer', /RANDALL PIKE/.test(qsSupp.synopsis), qsSupp.synopsis);
ok('quickScan summarises the narrative', /folding knife|responded to/.test(qsSupp.synopsis), qsSupp.synopsis);
eq('a supplement offers no offense to the create-case form', qsSupp.offenseList, []);

// The SUPP# column is not always printed.
const noSupp = SUPP.replace('INCIDENT NUMBER SUPP# |', 'INCIDENT NUMBER')
    .replace('26-0512833 4 06/11/2026', '26-0512833 06/11/2026');
eq('no SUPP# column means no supplement number', AR.parse(noSupp, 'x.pdf').supplementNo, '');
eq('the incident number still reads', AR.parse(noSupp, 'x.pdf').reportNumber, '26-0512833');

// The junk gate applies to supplements too.
const rsw = AR.parse(SUPP_WRECKED, 'wrecked sup.pdf');
eq('a wrecked supplement yields no narrative', rsw.narratives.length, 0);
eq('the header still reads on a wrecked supplement', rsw.reportNumber, '26-0512833');
ok('the wrecked supplement warns about the withheld page',
    rsw.diagnostics.warnings.some(w => /^Narrative text on page\(s\) 1\b/.test(w)),
    rsw.diagnostics.warnings);
eq('the wrecked supplement still offers page 1 to band OCR',
    AR.narrativeBandPages(rsw), [1]);

// Degrade, never throw.
[
    ['supplement title only', 'SUPPLEMENT NARRATIVE'],
    ['supplement header, no narrative',
        'SUPPLEMENT NARRATIVE\nINCIDENT NUMBER\n26-0512833\nSUPPLEMENTING OFFICER\nF4102 - RANDALL PIKE'],
    ['supplement with CRLF', SUPP.replace(/\n/g, '\r\n')],
    ['supplement reversed', SUPP.split('\n').reverse().join('\n')]
].forEach(([label, input]) => {
    let out = null, threw = null;
    try { out = AR.parse(input, 'x.pdf'); } catch (e) { threw = e; }
    ok('parse survives: ' + label, !threw, threw && threw.message);
    if (out) {
        ok('  ...returns arrays: ' + label,
            Array.isArray(out.offenses) && Array.isArray(out.personsInvolved) &&
            Array.isArray(out.narratives) && Array.isArray(out.provisionalPersons));
        ok('  ...narrative officer is always a string: ' + label,
            out.narratives.every(n => typeof n.officer === 'string'));
    }
    let q = null;
    try { q = AR.quickScan(input, 'x.pdf'); } catch (e) { q = null; }
    ok('quickScan survives: ' + label, !!q);
});
const crlfSupp = AR.parse(SUPP.replace(/\n/g, '\r\n'), 'x.pdf');
eq('CRLF yields the same supplement narrative',
    crlfSupp.narratives[0].text, rs.narratives[0].text);

/* ────────────────────────────────────────────────────────────────
 * 19. AUTHORITATIVE PAGE NUMBERS.
 *
 *     Page ordinals used to be inferred from the printed "INCIDENT
 *     REPORT" / "CONTINUATION PAGE" banner. On the Faulkner scan of
 *     26-0905538 the banner is a rotated left-margin element that OCR'd
 *     as punctuation on five of nine pages, so a NINE page PDF was read
 *     as five logical pages. Every page-addressed recovery pass then
 *     aimed at the wrong page and the narrative came back empty.
 *
 *     extract-pdf-text now hands over the real per-page text. The
 *     contract is exact — it builds its flat text as
 *     `pages.join('\n') + '\n'` — and a page array that does not
 *     reconcile with the text is REJECTED rather than trusted, because
 *     a page number that is quietly wrong is worse than one that is
 *     openly guessed.
 * ──────────────────────────────────────────────────────────────── */
console.log('\n[authoritative pages]');
const splitPages = AR._internal.splitPages;
const flatten = (pageTexts) => pageTexts.join('\n') + '\n';
const linesOf = (t) => String(t).replace(/\r\n?/g, '\n').split('\n');

const P3 = [
    "INCIDENT REPORT\nAGENCY NAME: Boone County Sheriff's Office\nINCIDENT NUMBER 26-0417295",
    'ARRESTEE # 1\nNAME: Last, First, Middle\nMARCHETTI, ROWENA CLAIRE',
    'CONTINUATION PAGE\nOthers Involved\nOTHER\nNAME: Last, First, Middle'
];
const a3 = splitPages(linesOf(flatten(P3)), P3);
ok('a reconciled page array is flagged authoritative', a3.authoritative === true);
eq('the page count comes from the PDF', a3.pages.length, 3);
eq('page ordinals are 1..3', a3.pages.map(p => p.index), [1, 2, 3]);
eq('page bounds are contiguous and cover the text',
    a3.bounds, [[0, 3], [3, 6], [6, 10]]);
eq('each page keeps its own lines', a3.pages[1].lines[2], 'MARCHETTI, ROWENA CLAIRE');
eq('continuation is answered from the real page, not the banner position',
    a3.pages.map(p => p.isContinuation), [false, false, true]);
eq('an authoritative split raises no warning', a3.warning, '');

// The regression itself: the identical text, inferred from banners, undercounts.
eq('banner inference collapses the same three pages into two',
    splitPages(linesOf(flatten(P3))).pages.length, 2);

const badPages = splitPages(linesOf(flatten(P3)), ['NOT THE SAME TEXT', 'AT ALL']);
ok('a page array that does not reconcile is rejected', badPages.authoritative === false);
ok('...and the reader is told page numbers were inferred instead',
    /did not match/.test(badPages.warning), badPages.warning);
eq('...and the banner inference still yields pages', badPages.pages.length, 2);

ok('a short page array is rejected rather than truncating the report',
    splitPages(linesOf(flatten(P3)), [P3[0], P3[1]]).authoritative === false);
ok('a page array with a page too many is rejected',
    splitPages(linesOf(flatten(P3)), P3.concat(['EXTRA PAGE'])).authoritative === false);
eq('an empty page array falls back silently',
    splitPages(linesOf(flatten(P3)), []).warning, '');
ok('a null page array falls back silently',
    splitPages(linesOf(flatten(P3)), null).authoritative === false);

/* A page array that AGREES with the banners must change nothing. This is the
 * guard on every existing fixture: threading real page text through must not
 * move a single field. */
const bannerPages = pages.map(p => p.lines.join('\n'));
// `r` has been mutated in place by the recoverNames() section above, so the
// baseline has to be a fresh parse of the same text.
const rBase = AR.parse(TEXT, 'Incident Report - Boone Arkansas.pdf');
const rMirror = AR.parse(flatten(bannerPages), 'Incident Report - Boone Arkansas.pdf',
    { pageTexts: bannerPages });
ok('the mirrored split is authoritative', rMirror.arPagesAuthoritative === true);
ok('the banner-inferred parse is not', rBase.arPagesAuthoritative === false);
eq('an agreeing page array changes no person',
    rMirror.personsInvolved, rBase.personsInvolved);
eq('...no provisional person', rMirror.provisionalPersons, rBase.provisionalPersons);
eq('...no offense', rMirror.offenses, rBase.offenses);
eq('...no narrative', rMirror.narratives.map(n => n.text), rBase.narratives.map(n => n.text));
eq('...and no page count', rMirror.pageCount, rBase.pageCount);
eq('...and no warning', rMirror.diagnostics.warnings, rBase.diagnostics.warnings);
eq('...and no recovery target', rMirror.narrativeRecovery, rBase.narrativeRecovery);

// Page bounds are recorded so a later recovery pass re-slices identically.
eq('page bounds are published on the report', r.arPageBounds.length, 5);
eq('published bounds match the split', r.arPageBounds, pageSplit.bounds);

/* ────────────────────────────────────────────────────────────────
 * 20. THE IDENTITY / EMPLOYMENT BAND — licence, issuing state, SSN.
 *
 *     PSM 6 left-packs a printed row, so the label count and the value
 *     count do not agree whenever a cell is blank: the reference
 *     arrestee row prints FIVE labels and FOUR values. These are read
 *     by token SHAPE, never by column position — which is also what
 *     will let the same reader work on another agency's form.
 *
 *     Every assertion here is about refusing to guess. A wrong licence
 *     number on a person in a case file is not recoverable.
 * ──────────────────────────────────────────────────────────────── */
console.log('\n[identity band]');
const hir = AR._internal.harvestIdentityRow;
function harvestId(rows) {
    const person = {
        name: '', dob: '', dl: '', dlState: '', ssn: '',
        phone: '', employmentPhone: '', occupation: '', placeOfEmployment: ''
    };
    hir(rows, 0, rows.length, person);
    return person;
}

// The victim band prints the licence beside the NAME label.
const vId = harvestId([
    "VICTIM # NAME: Last, First, Middle SOC. SEC. NO. DRIVER'S LICENSE DR. LI. STATE | DATE OF BIRTH",
    '1 HOLLOWAY (JV2), MARISOL 934013641 AR 04/22/2011'
]);
eq('the licence number is the token left of the state code', vId.dl, '934013641');
eq('the issuing state is the state code itself', vId.dlState, 'AR');
eq('no SSN was printed, so none is claimed', vId.ssn, '');

// The arrestee band prints it beside RESIDENT PHONE / SSN.
const aId = harvestId([
    "ARRESTEE # RESIDENT PHONE EMPLOYMENT PHONE SSN DRIVER'S LICENSE DR. LI. STATE",
    '(501) 472-5938 (501) 555-0143 472-89-0060 933481021 AR'
]);
eq('the SSN is read from a labelled row', aId.ssn, '472-89-0060');
eq('the licence is read from the same row', aId.dl, '933481021');
eq('the issuing state is read from the same row', aId.dlState, 'AR');
eq('the first printed number is the resident phone', aId.phone, '(501) 472-5938');
eq('the second printed number is the employment phone', aId.employmentPhone, '(501) 555-0143');

// One number under two phone labels is ambiguous — it is the resident's.
const oneP = harvestId([
    'ARRESTEE # RESIDENT PHONE EMPLOYMENT PHONE SSN',
    '(501) 472-5938 472-89-0060'
]);
eq('a single number is the resident phone', oneP.phone, '(501) 472-5938');
eq('no employment phone is invented from one number', oneP.employmentPhone, '');
eq('the SSN is not mistaken for a phone number', oneP.ssn, '472-89-0060');

// Shape rejections — each of these sits immediately left of a state code.
eq('a city name is not a licence number',
    harvestId(["DRIVER'S LICENSE DR. LI. STATE", '912 THISTLEDOWN LN, Bellefonte, AR 72611']).dl, '');
eq('a date of birth is not a licence number',
    harvestId(["DRIVER'S LICENSE DR. LI. STATE", 'SMITH, JOHN 04/22/2011 AR']).dl, '');
eq('an SSN is not a licence number',
    harvestId(["DRIVER'S LICENSE DR. LI. STATE SSN", 'DOE, JANE 472-89-0060 AR']).dl, '');
eq('a ZIP code is not a licence number',
    harvestId(["DRIVER'S LICENSE DR. LI. STATE", 'DOE, JANE 72611 AR']).dl, '');
eq('with no state code, no licence is claimed',
    harvestId(["DRIVER'S LICENSE DR. LI. STATE", 'DOE, JANE 933481021']).dl, '');
eq('the state is never inferred from the resident address',
    harvestId(["DRIVER'S LICENSE DR. LI. STATE", 'DOE, JANE 933481021']).dlState, '');
eq('an unlabelled row yields no SSN',
    harvestId(["DRIVER'S LICENSE DR. LI. STATE", 'DOE, JANE 472-89-0060 933481021 AR']).ssn, '');
eq('...but the licence on that row still reads',
    harvestId(["DRIVER'S LICENSE DR. LI. STATE", 'DOE, JANE 472-89-0060 933481021 AR']).dl, '933481021');
eq('a blank value row yields nothing',
    harvestId(["DRIVER'S LICENSE DR. LI. STATE SSN", '', '| |']).dl, '');

/* ────────────────────────────────────────────────────────────────
 * 21. THE ARREST OFFENSE(S) CROSS-REFERENCE is a label, not a person.
 *
 *     "Arrestee #1: WINN, BRENTON CONNER" is printed inside the offence
 *     table. Reading it as a person block produced a phantom suspect
 *     wearing whichever date of birth happened to follow it. It is used
 *     for exactly one thing: naming a band whose NAME cell OCR lost,
 *     and only when the pairing cannot be anything else.
 * ──────────────────────────────────────────────────────────────── */
console.log('\n[arrestee cross-reference]');
const xref = AR._internal.arresteeXref;
eq('the offence-table cross-reference is recognised',
    xref('Arrestee #1: MARCHETTI, ROWENA CLAIRE'),
    { num: '1', name: 'MARCHETTI, ROWENA CLAIRE' });
eq('gutter noise before it is tolerated',
    xref('| Arrestee #2: DOE, JOHN Q.'), { num: '2', name: 'DOE, JOHN Q.' });
ok('the person-band template is NOT a cross-reference',
    xref("ARRESTEE # NAME: Last, First, Middle SOC. SEC. NO. DRIVER'S LICENSE") === null);
ok('a bare ARRESTEE # column header is not a cross-reference',
    xref('ARRESTEE #') === null);
ok('a cross-reference with nothing after the colon is rejected',
    xref('Arrestee #2:') === null);
ok('a cross-reference whose value is an address is rejected',
    xref('Arrestee #1: 164 S COKER RD') === null);
ok('a cross-reference with no comma is rejected',
    xref('Arrestee #1: UNKNOWN') === null);
ok('empty input', xref('') === null);
ok('null input', xref(null) === null);

/* ────────────────────────────────────────────────────────────────
 * 22. ONE ARRESTEE BAND PER ARREST OFFENCE.
 *
 *     The form reprints the whole person band for each charge, so one
 *     human appears two or three times on one page with the same typed
 *     values and a different offence in the last row. On 26-0905538 the
 *     first band carried the licence and the second the SSN, so the
 *     duplicate is merged INTO the first rather than discarded.
 *
 *     The merge demands agreement on at least two of DOB / licence /
 *     SSN / phone, treats any conflict in those as proof of a different
 *     person, and never crosses a page — a family sharing one address
 *     must not be collapsed.
 * ──────────────────────────────────────────────────────────────── */
console.log('\n[duplicate arrestee bands]');
const mdb = AR._internal.mergeDuplicateBands;
const band = (o) => Object.assign({
    involvement: AR.ROLE.ARRESTEE, name: '', dob: '', dl: '', ssn: '',
    phone: '', address: '', sourcePage: 2
}, o);

const dup = mdb([
    band({ dob: '12/11/1995', phone: '(501) 472-5938', dl: '933481021', address: '164 S COKER RD' }),
    band({ dob: '12/11/1995', phone: '(501) 472-5938', ssn: '472-89-0060' })
]);
eq('two prints of one person become one record', dup.length, 1);
eq('the licence from the first band survives', dup[0].dl, '933481021');
eq('the SSN from the second band is filled in', dup[0].ssn, '472-89-0060');
eq('the address is not lost', dup[0].address, '164 S COKER RD');

eq('a conflicting date of birth means two people',
    mdb([
        band({ dob: '12/11/1995', phone: '(501) 472-5938' }),
        band({ dob: '08/05/2022', phone: '(501) 472-5938' })
    ]).length, 2);
eq('a conflicting licence means two people',
    mdb([
        band({ dob: '12/11/1995', dl: '933481021', phone: '(501) 472-5938' }),
        band({ dob: '12/11/1995', dl: '934013641', phone: '(501) 472-5938' })
    ]).length, 2);
eq('one shared identifier is not enough',
    mdb([band({ dob: '12/11/1995' }), band({ dob: '12/11/1995' })]).length, 2);
eq('the merge never crosses a page',
    mdb([
        band({ sourcePage: 2, dob: '12/11/1995', phone: '(501) 472-5938' }),
        band({ sourcePage: 3, dob: '12/11/1995', phone: '(501) 472-5938' })
    ]).length, 2);
eq('the merge never crosses a role',
    mdb([
        band({ involvement: AR.ROLE.ARRESTEE, dob: '12/11/1995', phone: '(501) 472-5938' }),
        band({ involvement: AR.ROLE.VICTIM, dob: '12/11/1995', phone: '(501) 472-5938' })
    ]).length, 2);
eq('two different names are two people',
    mdb([
        band({ name: 'DOE, JOHN', dob: '12/11/1995', phone: '(501) 472-5938' }),
        band({ name: 'DOE, JANE', dob: '12/11/1995', phone: '(501) 472-5938' })
    ]).length, 2);
const namedDup = mdb([
    band({ name: '', dob: '12/11/1995', phone: '(501) 472-5938', dl: '933481021' }),
    band({ name: 'DOE, JOHN', dob: '12/11/1995', phone: '(501) 472-5938' })
]);
eq('a nameless print merges into its named twin', namedDup.length, 1);
eq('...and takes the name that was read', namedDup[0].name, 'DOE, JOHN');
eq('an empty list is handled', mdb([]), []);

/* ────────────────────────────────────────────────────────────────
 * 23. END TO END on a synthetic arrestee page — the cross-reference
 *     names the band, the duplicate prints merge, and the source of
 *     the name is disclosed.
 *
 *     Synthetic, LF, and modelled on the shape of 26-0905538 page 2
 *     with every value replaced.
 * ──────────────────────────────────────────────────────────────── */
console.log('\n[arrestee page, end to end]');
const ARR_PAGE = [
    'INCIDENT REPORT',
    'ARKANSAS',
    "AGENCY NAME: Boone County Sheriff's Office",
    'ORI NUMBER AR0450000',
    'INCIDENT NUMBER 26-0417295',
    'INCIDENT DATE 08/13/2026',
    'REPORTING OFFICER D0312 - DERRICK LANE',
    'CONTINUATION PAGE',
    'Arrest Offense(s)',
    'Arrestee #1: MARCHETTI, ROWENA CLAIRE',
    "ARRESTEE # NAME: Last, First, Middle SOC. SEC. NO. DRIVER'S LICENSE DR. LI. STATE DATE OF BIRTH",
    '1 ee ee 933481021 AR 12/11/1995',
    'RESIDENT ADDRESS: Street City State Zip',
    '164 S COKER RD, Vilonia, AR 72173',
    'RESIDENT PHONE',
    '(501) 472-5938',
    'OFFENSE DESCRIPTION BATTERY 2ND DEGREE',
    "ARRESTEE # NAME: Last, First, Middle SOC. SEC. NO. DRIVER'S LICENSE DR. LI. STATE DATE OF BIRTH",
    '2 aa aa 472-89-0060 12/11/1995',
    'RESIDENT PHONE',
    '(501) 472-5938',
    'OFFENSE DESCRIPTION FLEEING'
].join('\n');

const ra = AR.parse(ARR_PAGE, 'synthetic.pdf');
const arrestees = ra.personsInvolved.filter(p => p.involvement === AR.ROLE.ARRESTEE);
eq('the two printed bands import as one person', arrestees.length, 1);
eq('the cross-reference supplied the name', arrestees[0].name, 'MARCHETTI, ROWENA CLAIRE');
eq('the source of that name is recorded', arrestees[0].nameSource, 'Arrest Offense(s) box');
eq('the licence came from the first band', arrestees[0].dl, '933481021');
eq('the issuing state came with it', arrestees[0].dlState, 'AR');
eq('the SSN came from the second band', arrestees[0].ssn, '472-89-0060');
eq('the date of birth is the one printed on the band', arrestees[0].dob, '12/11/1995');
eq('the address survived the merge', arrestees[0].address, '164 S COKER RD, Vilonia, AR 72173');
eq('the phone survived the merge', arrestees[0].phone, '(501) 472-5938');
eq('the band is on page 2', arrestees[0].sourcePage, 2);
ok('the inferred name is disclosed to the reader',
    ra.diagnostics.warnings.some(w => /Arrest Offense\(s\) box/.test(w) && /Verify it/.test(w)),
    ra.diagnostics.warnings);
ok('the cross-reference is not itself imported as a person',
    !ra.personsInvolved.some(p => p.sourcePage === 2 && p !== arrestees[0] &&
        p.name === 'MARCHETTI, ROWENA CLAIRE'));
eq('nothing is left provisional', ra.provisionalPersons.length, 0);

// Two names in the box and one nameless band is a GUESS — refuse it and say so.
const ambiguous = AR.parse(
    ARR_PAGE.replace('Arrest Offense(s)\n', 'Arrest Offense(s)\nArrestee #2: QUILLEN, DELPHINE\n'),
    'synthetic.pdf');
eq('an ambiguous pairing names nobody',
    ambiguous.personsInvolved.filter(p => p.involvement === AR.ROLE.ARRESTEE).length, 0);
eq('...and the band is held as provisional', ambiguous.provisionalPersons.length, 1);
ok('...and the reason is disclosed',
    ambiguous.diagnostics.warnings.some(w => /no name was assigned/.test(w)),
    ambiguous.diagnostics.warnings);

/* ────────────────────────────────────────────────────────────────
 * 24. ONE "Others Involved" ROLE HEADING CAN COVER SEVERAL PEOPLE.
 *
 *     The continuation page prints "OTHER" once and then repeats the
 *     person template beneath it. Splitting on the heading alone
 *     collapsed them into a single record wearing the first person's
 *     date of birth and the last person's name — on 26-0905538 that
 *     produced a 51-year-old carrying a 4-year-old's DOB and dropped a
 *     whole person from the page before it.
 * ──────────────────────────────────────────────────────────────── */
console.log('\n[others involved — several people, one heading]');
const OTHERS_PAGE = [
    'INCIDENT REPORT',
    'ARKANSAS',
    "AGENCY NAME: Boone County Sheriff's Office",
    'ORI NUMBER AR0450000',
    'INCIDENT NUMBER 26-0417295',
    'INCIDENT DATE 08/13/2026',
    'REPORTING OFFICER D0312 - DERRICK LANE',
    'CONTINUATION PAGE',
    'Others Involved',
    'OTHER',
    'NAME: Last, First, Middle',
    'MARCHETTI, WRENLEIGH J (M) Male',
    'DATE OF BIRTH',
    '03/14/2014',
    'RESIDENT ADDRESS: Street City State Zip',
    '912 THISTLEDOWN LN, Bellefonte, AR 72611',
    'NAME: Last, First, Middle',
    'MARCHETTI, WESTON Z be [J (00) Unknown ot cs',
    'DATE OF BIRTH',
    '07/22/2016',
    'RESIDENT ADDRESS: Street City State Zip',
    '912 THISTLEDOWN LN, Bellefonte, AR 72611'
].join('\n');

const ro = AR.parse(OTHERS_PAGE, 'synthetic.pdf');
const oth = ro.personsInvolved.filter(p => /^Others Involved/.test(p.detail || ''));
eq('one heading yields two people', oth.length, 2);
eq('both names are read', oth.map(p => p.name),
    ['MARCHETTI, WRENLEIGH', 'MARCHETTI, WESTON Z']);
eq('each keeps its OWN date of birth', oth.map(p => p.dob), ['03/14/2014', '07/22/2016']);
eq('both carry the role from the heading', oth.map(p => p.involvement), ['OTHER', 'OTHER']);
eq('both are attributed to page 2', oth.map(p => p.sourcePage), [2, 2]);
eq('the heading is recorded on each', oth[0].detail, 'Others Involved — OTHER');

/* ────────────────────────────────────────────────────────────────
 * 25. THE MIDDLE INITIAL vs THE TICKED CHECKBOX.
 *
 *     A middle initial is printed without a full stop ("WINN, WESTON
 *     Z"), so the initial-needs-a-dot rule dropped it from every
 *     imported name. But a lone capital is ALSO exactly how OCR renders
 *     a ticked checkbox. On this form a checkbox glyph is always
 *     followed by its parenthesised option code — "I (0) Male",
 *     "J (M) Male" — and that is the only thing separating them.
 * ──────────────────────────────────────────────────────────────── */
console.log('\n[middle initials]');
eq('a bare middle initial is kept',
    xn('MARCHETTI, WESTON Z be [J (00) Unknown ot cs'), 'MARCHETTI, WESTON Z');
eq('...including at the end of a packed row',
    xn('MARCHETTI, AMANDA K = 5 op [J (00) Unknown = od fr'), 'MARCHETTI, AMANDA K');
eq('a capital followed by an option code is a checkbox, not an initial',
    xn('MARCHETTI, WRENLEIGH J (M) Male'), 'MARCHETTI, WRENLEIGH');
eq('...for the sex column too', xn('DOE, JANE F (F) Female'), 'DOE, JANE');
eq('an initial WITH a period still works', xn('DOE, JOHN Q.'), 'DOE, JOHN Q.');
eq('a two-letter glyph is still never a middle name',
    xn('Marchetti, Rowena Claire IH (F) Female Bl (W) White'), 'Marchetti, Rowena Claire');
eq('a middle initial does not swallow the row after it',
    xn('MARCHETTI, WESTON Z 07/22/2016'), 'MARCHETTI, WESTON Z');

console.log('\n' + (fail ? 'FAILED' : 'OK') + ' — ' + pass + ' passed, ' + fail + ' failed');
process.exit(fail ? 1 : 0);
